"""v1.4.163 — SF taker-fallback fill tagging.

Bug context: snapshot ``v1.4.157-260520-213540-prod.okx.ton.usdt.perp``
contained 3 fills at 17:15:00.757-758 that were the actual closing
fills of soft-flatten episode SF#11167. Those fills were generated by
the taker-fallback path in ``app/bot.py:2369``:

    self._client.market_close(self._settings.symbol)

That call bypasses ``ExecutionEngine.place_order`` entirely — no row
ever gets inserted into the local ``orders`` SQLite table for the
market-close order. When the resulting fills arrive at fill
ingestion, ``order_metadata_for_fill_ingest`` returns the all-None
dict (parent absent), and the fills end up with
``soft_flatten_event_id=None`` despite being SF-attributable.

Visible symptoms in production:
  - The SF chart markers' tooltip says "0 fills" for the episode
    (v1.4.162 marker-rendering fix surfaces the marker but the LEFT
    JOIN over ``fills`` returns 0 because the fills are untagged).
  - The fills-history UI doesn't tag those rows as SF.
  - ``live_stats._soft_flatten_attribution_block`` undercounts.
  - Postmortem joins on ``soft_flatten_event_id`` miss the closing
    fills entirely.

Fix: in ``fill_ingestion.ingest_hl_fill_raw``, when
``order_metadata_for_fill_ingest`` returns no SF tag AND
``parent_order_exists`` confirms the parent isn't in the local DB
AND ``state.soft_flatten_event_id`` is currently set, stamp the fill
with the active SF event id. The ``parent_order_exists`` check
distinguishes "taker-fallback case (NO parent)" from "pre-SF order
whose cancel raced a fill (parent present but untagged)" — only the
former should be stamped.

These tests cover the fix's correctness across the cases.
"""

from __future__ import annotations

import os
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path

from app.enums import Side
from app.exchange.hyperliquid_types import HLFillRaw
from app.fill_ingestion import ingest_hl_fill_raw
from app.models import PositionSnapshot
from app.pnl import PnlTracker
from app.state import BotState
from app.storage import Storage
from tests.settings_helpers import UnitTestSettings


def _settings() -> tuple[UnitTestSettings, Path]:
    path = (
        Path(tempfile.gettempdir())
        / f"mm_sftag_{os.getpid()}_{uuid.uuid4().hex}.db"
    )
    path.unlink(missing_ok=True)
    return (
        UnitTestSettings.model_validate(
            {
                "TRADING_ENABLED": True,
                "HL_SECRET_KEY": "x",
                "HL_ACCOUNT_ADDRESS": "0xabc",
                "DATABASE_URL": f"sqlite:///{path.as_posix()}",
            }
        ),
        path,
    )


def _setup(active_sf_id: int | None) -> tuple[
    Storage, BotState, PnlTracker, Path, UnitTestSettings
]:
    settings, path = _settings()
    storage = Storage(settings)
    storage.init_schema()
    state = BotState(settings)
    state.session_started_at_utc = datetime(
        2026, 5, 20, 16, 50, 0, tzinfo=timezone.utc
    )
    state.soft_flatten_event_id = active_sf_id
    pnl = PnlTracker()
    return storage, state, pnl, path, settings


def _fr(
    symbol: str,
    *,
    fill_id: str,
    oid: int,
    side: Side = Side.BUY,
    time_iso: str = "2026-05-20T17:15:00.757+00:00",
) -> HLFillRaw:
    return HLFillRaw(
        fill_id=fill_id,
        oid=oid,
        coin=symbol,
        side=side,
        px=2.059,
        sz=3.0,
        fee=0.0006,
        time_ms=int(
            datetime.fromisoformat(time_iso).timestamp() * 1000
        ),
        closed_pnl=-0.07,
        raw={},
    )


# ---------------------------------------------------------------------------
# Core fix: taker-fallback fills inherit the active SF tag
# ---------------------------------------------------------------------------


def test_taker_fallback_fill_inherits_active_sf_id() -> None:
    """Replay of the v1.4.157 failure. SF is active (id=11167), the
    bot calls market_close which produces a fill on an order id that
    has NO corresponding row in the local ``orders`` table. With the
    fix the fill row gets stamped with sf_event_id=11167."""
    storage, state, pnl, path, settings = _setup(active_sf_id=11167)
    try:
        fr = _fr(settings.symbol, fill_id="taker-1", oid=3583442235357601792)
        # Sanity: parent does NOT exist in the orders table.
        assert not storage.parent_order_exists(str(fr.oid))

        assert ingest_hl_fill_raw(
            state=state,
            storage=storage,
            pnl=pnl,
            symbol=settings.symbol,
            fr=fr,
            source="ws",
        )

        rows = storage.recent_fills(5)
        assert len(rows) == 1
        assert rows[0]["soft_flatten_event_id"] == 11167
    finally:
        path.unlink(missing_ok=True)


def test_fill_without_active_sf_not_tagged() -> None:
    """When SF is NOT active and no parent order exists in the DB
    (e.g., a fill arrives via REST catch-up for an order placed in a
    prior session), the fill is NOT spuriously tagged."""
    storage, state, pnl, path, settings = _setup(active_sf_id=None)
    try:
        fr = _fr(settings.symbol, fill_id="other-1", oid=999)
        assert ingest_hl_fill_raw(
            state=state,
            storage=storage,
            pnl=pnl,
            symbol=settings.symbol,
            fr=fr,
            source="rest",
        )
        rows = storage.recent_fills(5)
        assert len(rows) == 1
        assert rows[0]["soft_flatten_event_id"] is None
    finally:
        path.unlink(missing_ok=True)


def test_pre_sf_fill_with_existing_parent_not_overwritten() -> None:
    """A pre-SF order's cancel races with a fill — the fill arrives
    AFTER SF has been entered (state.soft_flatten_event_id set) but
    its parent is a PRE-SF order in the DB with soft_flatten_event_id
    legitimately NULL. The fix must NOT overwrite the NULL with the
    active SF id; the fill belongs to the prior regime."""
    storage, state, pnl, path, settings = _setup(active_sf_id=11167)
    try:
        # Insert a pre-SF order row directly into the orders table
        # with soft_flatten_event_id=NULL.
        with storage._lock:
            with storage.connection() as conn:
                conn.execute(
                    """
                    INSERT INTO orders (
                        order_id_local, order_id_exchange, client_order_id,
                        ts_created, symbol, side, price, size, post_only,
                        status, soft_flatten_event_id
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "local-pre-sf",
                        "999888",
                        "cl-pre-sf",
                        "2026-05-20T17:14:00.000+00:00",
                        settings.symbol,
                        "SELL",
                        2.041,
                        3.0,
                        1,
                        "CANCEL_PENDING",
                        None,  # NOT tagged — pre-SF order
                    ),
                )
        # Sanity: parent IS present.
        assert storage.parent_order_exists("999888")

        fr = _fr(
            settings.symbol,
            fill_id="pre-sf-race",
            oid=999888,
            side=Side.SELL,
        )
        assert ingest_hl_fill_raw(
            state=state,
            storage=storage,
            pnl=pnl,
            symbol=settings.symbol,
            fr=fr,
            source="ws",
        )

        rows = storage.recent_fills(5)
        assert len(rows) == 1
        # CRITICAL: the fix must NOT stamp this fill with the active
        # SF id, because the fill is from a pre-SF order.
        assert rows[0]["soft_flatten_event_id"] is None
    finally:
        path.unlink(missing_ok=True)


def test_taker_fallback_fill_when_oid_present_and_tagged_no_change() -> None:
    """Sanity: when a parent row DOES exist AND IS tagged with the SF
    id, the fix is a no-op — the tag comes from the parent via the
    normal lookup path."""
    storage, state, pnl, path, settings = _setup(active_sf_id=42)
    try:
        with storage._lock:
            with storage.connection() as conn:
                conn.execute(
                    """
                    INSERT INTO orders (
                        order_id_local, order_id_exchange, client_order_id,
                        ts_created, symbol, side, price, size, post_only,
                        status, soft_flatten_event_id
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "local-sf",
                        "555444",
                        "cl-sf",
                        "2026-05-20T17:14:50.000+00:00",
                        settings.symbol,
                        "BUY",
                        2.052,
                        3.0,
                        1,
                        "ACKED",
                        42,  # tagged
                    ),
                )
        fr = _fr(settings.symbol, fill_id="passive-sf", oid=555444)
        assert ingest_hl_fill_raw(
            state=state,
            storage=storage,
            pnl=pnl,
            symbol=settings.symbol,
            fr=fr,
            source="ws",
        )
        rows = storage.recent_fills(5)
        assert len(rows) == 1
        assert rows[0]["soft_flatten_event_id"] == 42
    finally:
        path.unlink(missing_ok=True)


def test_storage_parent_order_exists_helper() -> None:
    """Direct test of the new ``parent_order_exists`` storage helper:
    True for present rows, False for absent."""
    storage, state, pnl, path, settings = _setup(active_sf_id=None)
    try:
        assert storage.parent_order_exists("does_not_exist") is False
        with storage._lock:
            with storage.connection() as conn:
                conn.execute(
                    """
                    INSERT INTO orders (
                        order_id_local, order_id_exchange, client_order_id,
                        ts_created, symbol, side, price, size, post_only,
                        status
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "local-1",
                        "abc123",
                        "cl-1",
                        "2026-05-20T17:00:00.000+00:00",
                        settings.symbol,
                        "BUY",
                        2.0,
                        3.0,
                        1,
                        "ACKED",
                    ),
                )
        assert storage.parent_order_exists("abc123") is True
        # Type coercion: integer arg should also work.
        assert storage.parent_order_exists(123) is False
    finally:
        path.unlink(missing_ok=True)
