"""Backtest-fixture regression suite (Phase 4 — v1.4.235).

Tests in this package replay recorded market data and assert no
regression against captured baselines.

Auto-skip behaviour: every test here uses ``@pytest.mark.skipif``
gating on ``backtesting/data/sessions/`` (or ``fixtures/``) being
non-empty. The CI daemon's worktree has neither directory populated
(both are gitignored), so the entire suite skips → green. Operator's
laptop has fixtures → tests actually exercise.

The baseline JSONs live in ``tests/backtest/baselines/<fixture>.json``
and are generated by ``scripts/backtest/capture_baseline.py``.
"""
